//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenASF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_PERSONALES
    {
        public long LLAVE_DATO_PERSONAL { get; set; }
        public Nullable<long> LLAVE_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string CIUDAD { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string COLONIA { get; set; }
        public string TELEFONO { get; set; }
        public string OTRO_TEL { get; set; }
        public Nullable<System.DateTime> FECHA_NAC { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string PASAPORTE { get; set; }
        public string CARTILLA { get; set; }
        public string GENERO { get; set; }
        public string EDO_CIVIL { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string MUN { get; set; }
        public string EDO { get; set; }
    }
}
