//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenASF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public long LLAVE_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string PASS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
    }
}
